"""Validate bounded openFDA registration/listing discovery without network access."""
from __future__ import annotations
import json
from pathlib import Path
from typing import Any

PROGRAMME_PATH=Path("curation/openfda_registration_listing_discovery_programme_v0.1.json")
UNIVERSE_REGISTRY_PATH=Path("curation/source_universe_registry_v0.1.json")
EXPECTED_QUERY_IDS={"DISCOVERY-OPENFDA-REGLIST-BCI-001","DISCOVERY-OPENFDA-REGLIST-DBS-NEUROSTIM-001","DISCOVERY-OPENFDA-REGLIST-NEUROPROSTHESIS-001","DISCOVERY-OPENFDA-REGLIST-VISUAL-NEUROPROSTHESIS-001","DISCOVERY-OPENFDA-REGLIST-NEURAL-RECORDING-001"}
REQUIRED_FIELDS={"representation_identity","registration_number","fei_number","registration_name","registration_status_code","registration_expiry_year","owner_operator_number","establishment_type","product_code","product_created_date","product_exempt","device_class","device_name","regulation_number","proprietary_names","k_number","pma_number","query_memberships","normalized_record_sha256"}
REQUIRED_COVERAGE={"supplied_page_count","returned_provider_record_count","expanded_representation_count","unique_representation_count","reported_total_count","reported_total_count_state","skip_sequence_valid","skip_coverage_state","over_26000_limit","bulk_download_or_partition_required","known_controlled_duplicate_count","new_candidate_count","duplicate_representation_count","unresolved_registration_number_count","unresolved_owner_operator_number_count","unresolved_product_code_count"}

def _load(p:Path)->Any:return json.loads(p.read_text(encoding="utf-8"))
def _require(c:bool,m:str)->None:
    if not c:raise ValueError(m)
def _universe(reg:dict[str,Any],uid:str)->dict[str,Any]:
    rows=reg.get("universes");_require(isinstance(rows,list),"Source-universe registry must contain universes");matches=[r for r in rows if r.get("universe_id")==uid];_require(len(matches)==1,f"Expected exactly one {uid} universe");return matches[0]

def validate_programme(p:dict[str,Any],reg:dict[str,Any])->dict[str,Any]:
    _require(p.get("programme_id")=="SU-REGULATION-OPENFDA-REGISTRATION-LISTING-v0.1","Unexpected programme_id");_require(p.get("status")=="NONCANONICAL_PROGRAMME_CONTROL","Programme must remain noncanonical");_require(p.get("source_universe_id")=="SU-REGULATION","Programme must bind SU-REGULATION");_require(p.get("source_system")=="OPENFDA_DEVICE_REGISTRATION_LISTING","Unexpected source system");_require(_universe(reg,"SU-REGULATION").get("canonical_completeness_claim") is False,"SU-REGULATION must not claim completeness")
    provider=p.get("provider_contract") or {};_require(provider.get("endpoint")=="https://api.fda.gov/device/registrationlisting.json","Endpoint changed");_require(provider.get("provider_update_frequency")=="MONTHLY","Provider cadence changed");_require(provider.get("max_records_per_request")==1000 and provider.get("max_skip")==25000 and provider.get("max_direct_result_count")==26000,"Provider paging bounds changed");_require(provider.get("bulk_download_requires_all_files_for_complete_current_dataset") is True,"Bulk completeness boundary changed");_require(provider.get("old_records_may_change_on_provider_update") is True,"Provider update boundary changed");_require(provider.get("configuration_performs_http") is False,"Programme configuration must not perform HTTP")
    dep=p.get("workbench_dependency") or {};_require(dep.get("required_capability")=="project_openfda_registration_listing_pages","Unexpected Workbench capability");_require(dep.get("integration_state")=="NOT_IMPLEMENTED","Registration/listing projector must remain NOT_IMPLEMENTED until implemented")
    ident=p.get("identity_policy") or {};_require(ident.get("provider_exposes_no_stable_listing_number_in_v0_1_surface") is True,"Stable listing-number assumption prohibited");_require(ident.get("representation_identity")=="REGISTRATION_NUMBER_PLUS_OWNER_OPERATOR_PLUS_PRODUCT_CODE_PLUS_PROPRIETARY_NAME_SET_DIGEST","Representation identity changed");_require(ident.get("representation_identity_is_not_exact_device_identity") is True,"Representation cannot become exact device identity");_require(ident.get("registration_number_is_establishment_registration_not_device_identity") is True,"Registration number cannot become device identity");_require(ident.get("changed_proprietary_name_set_requires_successor_or_identity_review") is True,"Name-set change review required")
    for k in ("fei_number_auto_entity_merge","owner_operator_number_auto_entity_merge","product_code_auto_system_merge","proprietary_name_auto_system_merge","k_number_auto_authorization_relationship","pma_number_auto_authorization_relationship"):_require(ident.get(k) is False,f"{k} must remain false")
    inc=p.get("inclusion_policy") or {}
    for k in ("automatic_source_admission","automatic_establishment_entity_creation","automatic_owner_operator_entity_creation","automatic_device_or_system_entity_creation","automatic_registration_relationship_creation","automatic_premarket_authorization_relationship_creation","automatic_marketing_authorization_claim_creation","automatic_clearance_or_approval_claim_creation","automatic_current_commercial_availability_claim_creation","automatic_system_conformance_claim_creation","automatic_assessment_mutation","automatic_reopening_decision","automatic_monitor_creation"):_require(inc.get(k) is False,f"{k} must remain false")
    _require(inc.get("human_relevance_review_required") is True,"Human review required")
    paging=p.get("paging_policy") or {};_require(paging.get("execution_mode_v0_1")=="SKIP_LIMIT_BOUNDED","Paging mode changed");_require(paging.get("page_limit")==1000 and paging.get("max_skip")==25000 and paging.get("max_direct_result_count")==26000,"Paging bounds changed");_require(paging.get("silent_truncation_allowed") is False and paging.get("partial_over_limit_candidate_emission_allowed") is False,"Silent/partial truncation prohibited");_require(paging.get("bulk_download_not_yet_authorized_by_v0_1_projector") is True,"v0.1 must not silently use bulk")
    streams=p.get("query_streams");_require(isinstance(streams,list),"query_streams required");ids=[str(r.get("query_id") or "") for r in streams];_require(len(ids)==len(set(ids)) and set(ids)==EXPECTED_QUERY_IDS,"Registration/listing query stream set changed")
    for r in streams:_require(r.get("cadence")=="MONTHLY" and r.get("status")=="ACTIVE",f"{r.get('query_id')}: cadence/status changed");_require(r.get("completeness_claim") is False,f"{r.get('query_id')}: cannot claim completeness");_require(isinstance(r.get("search"),str) and ("proprietary_name:" in r["search"] or "products.openfda.device_name:" in r["search"]),f"{r.get('query_id')}: provider search required")
    proj=p.get("candidate_projection") or {};_require(set(proj.get("required_fields") or [])==REQUIRED_FIELDS,"Candidate field contract changed")
    for k in ("registration_address_fields_in_discovery_layer","owner_operator_contact_fields_in_discovery_layer","us_agent_fields_in_discovery_layer","official_correspondent_fields_in_discovery_layer","raw_api_pages_emitted_to_s2"):_require(proj.get(k) is False,f"{k} must remain false")
    cov=p.get("coverage_contract") or {};_require(set(cov.get("required_metrics_per_leaf_query") or [])==REQUIRED_COVERAGE,"Coverage metrics changed");_require(cov.get("mechanical_completion_requires")=={"reported_total_count_state":"CONSISTENT","skip_sequence_valid":True,"skip_coverage_state":"MATCH","over_26000_limit":False,"bulk_download_or_partition_required":False},"Mechanical completion contract changed")
    for k in ("registration_listing_database_completeness_claim","global_neuroai_registration_listing_coverage_claim","query_recall_claim","registration_or_listing_is_marketing_authorization_claim","registration_or_listing_is_clearance_or_approval_claim","k_or_pma_reference_is_exact_configuration_authorization_claim","product_code_is_exact_device_identity_claim"):_require(cov.get(k) is False,f"{k} must remain false")
    review=p.get("human_review_contract") or {}
    for k in ("automatic_acceptance","registration_or_listing_is_marketing_authorization_evidence","registration_or_listing_is_clearance_or_approval_evidence","k_or_pma_reference_establishes_exact_assessed_configuration","product_code_establishes_exact_device_identity","registration_listing_record_automatically_reopens_assessment"):_require(review.get(k) is False,f"{k} must remain false")
    net=p.get("network_policy") or {};_require(net.get("live_execution")=="OPT_IN_ONLY" and net.get("requires_workbench_network_gate") is True,"Network boundary changed");_require(net.get("configuration_performs_http") is False and net.get("hosted_success_claim_allowed_without_runner_steps") is False,"Execution-status boundary changed")
    return {"programme_id":p["programme_id"],"query_stream_count":len(streams),"integration_state":dep["integration_state"],"network_requests_performed":False,"exact_device_identity_claim_created":False,"authorization_claim_created":False,"automatic_reopening":False,"canonical_mutation_performed":False}

def main()->None:print(json.dumps(validate_programme(_load(PROGRAMME_PATH),_load(UNIVERSE_REGISTRY_PATH)),indent=2,sort_keys=True))
if __name__=="__main__":main()
