"""Validate bounded SU-PATENTS EPO OPS discovery without network access."""
from __future__ import annotations
import json
from pathlib import Path
from typing import Any
PROGRAMME_PATH=Path("curation/epo_ops_patent_discovery_programme_v0.1.json");UNIVERSE_REGISTRY_PATH=Path("curation/source_universe_registry_v0.1.json")
EXPECTED_IDS={"DISCOVERY-OPS-BCI-001","DISCOVERY-OPS-INVASIVE-NEURAL-001","DISCOVERY-OPS-CLOSED-LOOP-NEUROMODULATION-001","DISCOVERY-OPS-NEURAL-DECODING-AI-001","DISCOVERY-OPS-VISUAL-NEUROPROSTHESIS-001","DISCOVERY-OPS-GREY-MENTAL-STATE-001","DISCOVERY-OPS-GREY-NEURAL-BIOMETRIC-001","DISCOVERY-OPS-GREY-WORKPLACE-ATTENTION-001","DISCOVERY-OPS-KNOWN-APPLICANTS-001"}
REQUIRED_FIELDS={"docdb_publication_reference","country","document_number","kind_code","title","publication_date","applicants","inventors","ipc_symbols","cpc_symbols","application_references","priority_references","query_memberships","normalized_record_sha256"}
REQUIRED_COVERAGE={"requested_range_count","returned_publication_reference_count","unique_docdb_publication_count","reported_total_result_count","reported_total_result_count_state","range_sequence_valid","range_coverage_state","over_2000_limit","partition_required","known_controlled_duplicate_count","new_candidate_count","cross_query_duplicate_representation_count","unresolved_docdb_identity_count"}
def _load(p:Path)->Any:return json.loads(p.read_text(encoding="utf-8"))
def _require(c:bool,m:str)->None:
    if not c:raise ValueError(m)
def _universe(reg:dict[str,Any],uid:str)->dict[str,Any]:
    rows=reg.get("universes");_require(isinstance(rows,list),"Source-universe registry must contain universes");matches=[r for r in rows if r.get("universe_id")==uid];_require(len(matches)==1,f"Expected exactly one {uid} universe");return matches[0]
def validate_programme(p:dict[str,Any],reg:dict[str,Any])->dict[str,Any]:
    _require(p.get("programme_id")=="SU-PATENTS-EPO-OPS-v0.1" and p.get("status")=="NONCANONICAL_PROGRAMME_CONTROL","Programme identity/state changed");_require(p.get("source_universe_id")=="SU-PATENTS" and p.get("source_system")=="EPO_OPS","Programme universe/system changed");_require(_universe(reg,"SU-PATENTS").get("canonical_completeness_claim") is False,"SU-PATENTS must not claim completeness")
    provider=p.get("provider_contract") or {};_require(provider.get("server")=="https://ops.epo.org/3.2/rest-services" and provider.get("search_endpoint")=="/published-data/search/biblio" and provider.get("search_constituent")=="biblio","OPS endpoint/constituent changed");_require(provider.get("query_language")=="CQL" and provider.get("response_media_type")=="application/exchange+xml" and provider.get("range_transport")=="X-OPS-Range","OPS request contract changed");_require(provider.get("max_records_per_range")==100 and provider.get("max_retrievable_results_per_search")==2000,"OPS retrieval bounds changed");_require(provider.get("configuration_performs_http") is False,"Programme must not perform HTTP")
    dep=p.get("workbench_dependency") or {};_require(dep.get("required_capability")=="project_epo_ops_search_pages" and dep.get("integration_state")=="AVAILABLE","Merged EPO OPS projector must be AVAILABLE")
    ident=p.get("identity_policy") or {};_require(ident.get("primary_identity")=="DOCDB_PUBLICATION_REFERENCE" and ident.get("required_identity_parts")==["country","document_number","kind_code"],"DOCDB identity changed")
    for k in ("publication_step_auto_merge","patent_family_auto_merge","fuzzy_title_identity_merge_allowed","applicant_name_auto_entity_merge","inventor_name_auto_entity_merge"):_require(ident.get(k) is False,f"{k} must remain false")
    _require(ident.get("conflicting_same_publication_policy")=="FAIL_CLOSED" and ident.get("family_relationship_requires_explicit_family_retrieval") is True,"Identity/family boundary changed")
    inc=p.get("inclusion_policy") or {}
    for k in ("automatic_patent_source_admission","automatic_patent_family_creation","automatic_applicant_or_inventor_entity_creation","automatic_product_or_system_relationship_creation","automatic_capability_claim_creation","automatic_assessment_mutation","automatic_monitor_creation"):_require(inc.get(k) is False,f"{k} must remain false")
    _require(inc.get("human_relevance_review_required") is True,"Human review required")
    part=p.get("search_partition_policy") or {};_require(part.get("initial_range")=="1-100" and part.get("subsequent_range_size")==100 and part.get("leaf_query_max_total_result_count")==2000,"OPS range/leaf bounds changed");_require(part.get("over_limit_policy")=="SPLIT_QUERY_BEFORE_MATERIALIZATION" and part.get("silent_truncation_allowed") is False and part.get("partial_over_limit_candidate_emission_allowed") is False and part.get("partition_provenance_required") is True,"Partition boundary changed")
    streams=p.get("query_streams");_require(isinstance(streams,list),"query_streams required");ids=[str(r.get("query_id") or "") for r in streams];_require(len(ids)==len(set(ids)) and set(ids)==EXPECTED_IDS,"OPS query stream set changed")
    watch=next(r for r in streams if r["query_id"]=="DISCOVERY-OPS-KNOWN-APPLICANTS-001");_require(watch.get("query_mode")=="APPLICANT_WATCH_SET" and len(watch.get("applicant_terms") or [])==8 and watch.get("cql_template")=="pa=\"{applicant_term}\"","Applicant watch contract changed")
    for r in streams:_require(r.get("status")=="ACTIVE" and r.get("completeness_claim") is False,f"{r.get('query_id')}: status/completeness changed")
    proj=p.get("candidate_projection") or {};_require(set(proj.get("required_fields") or [])==REQUIRED_FIELDS,"Candidate field contract changed");_require(proj.get("claims_or_description_capture_in_discovery_layer") is False and proj.get("facsimile_or_image_capture_in_discovery_layer") is False and proj.get("raw_ops_xml_emitted_to_s2") is False,"Patent projection minimization changed")
    cov=p.get("coverage_contract") or {};_require(set(cov.get("required_metrics_per_leaf_query") or [])==REQUIRED_COVERAGE,"Coverage metrics changed");_require(cov.get("mechanical_completion_requires")=={"reported_total_result_count_state":"CONSISTENT","range_sequence_valid":True,"range_coverage_state":"MATCH","over_2000_limit":False,"partition_required":False},"Mechanical completion contract changed")
    for k in ("epo_database_completeness_claim","global_neuroai_patent_recall_claim","query_recall_claim","patent_family_completeness_claim"):_require(cov.get(k) is False,f"{k} must remain false")
    review=p.get("human_review_contract") or {};_require(review.get("automatic_acceptance") is False,"Automatic acceptance prohibited")
    for k in ("patent_existence_is_capability_evidence","patent_existence_is_product_implementation_evidence","patent_existence_is_freedom_to_operate_evidence","patent_existence_is_validity_or_enforceability_determination"):_require(review.get(k) is False,f"{k} must remain false")
    net=p.get("network_policy") or {};_require(net.get("live_execution")=="OPT_IN_CREDENTIALLED_ONLY" and net.get("requires_epo_ops_credentials") is True and net.get("requires_workbench_network_gate") is True and net.get("configuration_performs_http") is False and net.get("credentials_or_tokens_may_be_committed") is False and net.get("hosted_success_claim_allowed_without_runner_steps") is False,"Network/credential boundary changed")
    return {"programme_id":p["programme_id"],"query_stream_count":len(streams),"integration_state":dep["integration_state"],"network_requests_performed":False,"canonical_mutation_performed":False,"global_patent_recall_claim":False}
def main()->None:print(json.dumps(validate_programme(_load(PROGRAMME_PATH),_load(UNIVERSE_REGISTRY_PATH)),indent=2,sort_keys=True))
if __name__=="__main__":main()
