"""Validate bounded openFDA device-classification discovery without network access."""
from __future__ import annotations
import json
from pathlib import Path
from typing import Any
PROGRAMME_PATH=Path("curation/openfda_device_classification_discovery_programme_v0.1.json");UNIVERSE_REGISTRY_PATH=Path("curation/source_universe_registry_v0.1.json")
EXPECTED_QUERY_IDS={"DISCOVERY-OPENFDA-CLASS-BCI-001","DISCOVERY-OPENFDA-CLASS-DBS-NEUROSTIM-001","DISCOVERY-OPENFDA-CLASS-NEUROPROSTHESIS-001","DISCOVERY-OPENFDA-CLASS-VISUAL-NEUROPROSTHESIS-001","DISCOVERY-OPENFDA-CLASS-NEURAL-RECORDING-001"}
REQUIRED_FIELDS={"product_code","record_identity","device_name","definition","device_class","classification_finality","regulation_number","medical_specialty","medical_specialty_description","review_code","implant_flag","life_sustain_support_flag","gmp_exempt_flag","query_memberships","normalized_record_sha256"}
REQUIRED_COVERAGE={"supplied_page_count","returned_record_count","unique_product_code_count","reported_total_count","reported_total_count_state","skip_sequence_valid","skip_coverage_state","over_26000_limit","bulk_download_or_partition_required","known_controlled_duplicate_count","new_candidate_count","duplicate_representation_count","unresolved_product_code_count","regulation_referenced_classification_count","proposed_not_final_classification_count"}
def _load(p:Path)->Any:return json.loads(p.read_text(encoding="utf-8"))
def _require(c:bool,m:str)->None:
    if not c:raise ValueError(m)
def _universe(reg:dict[str,Any],uid:str)->dict[str,Any]:
    rows=reg.get("universes");_require(isinstance(rows,list),"Source-universe registry must contain universes");matches=[r for r in rows if r.get("universe_id")==uid];_require(len(matches)==1,f"Expected exactly one {uid} universe");return matches[0]
def validate_programme(p:dict[str,Any],reg:dict[str,Any])->dict[str,Any]:
    _require(p.get("programme_id")=="SU-REGULATION-OPENFDA-DEVICE-CLASSIFICATION-v0.1","Unexpected programme_id");_require(p.get("status")=="NONCANONICAL_PROGRAMME_CONTROL","Programme must remain noncanonical");_require(p.get("source_universe_id")=="SU-REGULATION","Programme must bind SU-REGULATION");_require(_universe(reg,"SU-REGULATION").get("canonical_completeness_claim") is False,"SU-REGULATION must not claim completeness")
    provider=p.get("provider_contract") or {};_require(provider.get("endpoint")=="https://api.fda.gov/device/classification.json","Endpoint changed");_require(provider.get("primary_record_id_field")=="product_code","Product-code identity changed");_require(provider.get("provider_update_frequency")=="MONTHLY","Provider cadence changed");_require(provider.get("max_records_per_request")==1000 and provider.get("max_skip")==25000 and provider.get("max_direct_result_count")==26000,"Paging bounds changed");_require(provider.get("bulk_download_requires_all_files_for_complete_current_dataset") is True,"Bulk completeness boundary changed");_require(provider.get("configuration_performs_http") is False,"Programme configuration must not perform HTTP")
    dep=p.get("workbench_dependency") or {};_require(dep.get("required_capability")=="project_openfda_device_classification_pages","Unexpected Workbench capability");_require(dep.get("integration_state")=="AVAILABLE","Merged classification projector must be AVAILABLE")
    ident=p.get("identity_policy") or {};_require(ident.get("record_identity")=="EXACT_PRODUCT_CODE","Classification identity changed");_require(ident.get("product_code_identifies_generic_device_category_not_exact_device") is True,"Product code must remain generic category")
    for k in ("device_name_auto_system_merge","regulation_number_auto_authorization_relationship","review_code_auto_authorization_relationship","openfda_harmonized_fields_auto_identity_merge"):_require(ident.get(k) is False,f"{k} must remain false")
    finality=p.get("classification_finality_policy") or {};_require(finality.get("regulation_number_present_state")=="REGULATION_REFERENCED_CLASSIFICATION","Finality state changed");_require(finality.get("regulation_number_absent_state")=="PROPOSED_CLASS_NOT_FINAL","Proposed state changed");_require(finality.get("absence_of_regulation_number_means_device_not_yet_classified_and_listed_class_is_proposed") is True,"Missing regulation-number semantics changed");_require(finality.get("device_class_without_regulation_number_must_not_be_presented_as_final") is True,"Proposed class cannot be final")
    inc=p.get("inclusion_policy") or {}
    for k in ("automatic_source_admission","automatic_device_or_system_entity_creation","automatic_product_code_relationship_creation","automatic_regulation_relationship_creation","automatic_marketing_authorization_claim_creation","automatic_clearance_or_approval_claim_creation","automatic_exact_device_identity_claim_creation","automatic_system_conformance_claim_creation","automatic_assessment_mutation","automatic_reopening_decision","automatic_monitor_creation"):_require(inc.get(k) is False,f"{k} must remain false")
    _require(inc.get("human_relevance_review_required") is True,"Human review required")
    paging=p.get("paging_policy") or {};_require(paging.get("execution_mode_v0_1")=="SKIP_LIMIT_BOUNDED","Paging mode changed");_require(paging.get("page_limit")==1000 and paging.get("max_skip")==25000 and paging.get("max_direct_result_count")==26000,"Paging bounds changed");_require(paging.get("silent_truncation_allowed") is False and paging.get("partial_over_limit_candidate_emission_allowed") is False,"Silent truncation prohibited")
    streams=p.get("query_streams");_require(isinstance(streams,list),"query_streams required");ids=[str(r.get("query_id") or "") for r in streams];_require(len(ids)==len(set(ids)) and set(ids)==EXPECTED_QUERY_IDS,"Classification query set changed")
    for r in streams:_require(r.get("cadence")=="MONTHLY" and r.get("status")=="ACTIVE",f"{r.get('query_id')}: cadence/status changed");_require(r.get("completeness_claim") is False,f"{r.get('query_id')}: cannot claim completeness")
    proj=p.get("candidate_projection") or {};_require(set(proj.get("required_fields") or [])==REQUIRED_FIELDS,"Candidate field contract changed");_require(proj.get("openfda_harmonized_identity_fields_in_projection") is False and proj.get("raw_api_pages_emitted_to_s2") is False,"Projection boundary changed")
    cov=p.get("coverage_contract") or {};_require(set(cov.get("required_metrics_per_leaf_query") or [])==REQUIRED_COVERAGE,"Coverage metrics changed");_require(cov.get("mechanical_completion_requires")=={"reported_total_count_state":"CONSISTENT","skip_sequence_valid":True,"skip_coverage_state":"MATCH","over_26000_limit":False,"bulk_download_or_partition_required":False,"unresolved_product_code_count":0},"Mechanical completion contract changed")
    for k in ("classification_database_completeness_claim","global_neuroai_classification_coverage_claim","query_recall_claim","product_code_is_exact_device_identity_claim","classification_record_is_marketing_authorization_claim","classification_record_is_clearance_or_approval_claim","device_class_is_system_conformance_claim"):_require(cov.get(k) is False,f"{k} must remain false")
    review=p.get("human_review_contract") or {}
    for k in ("automatic_acceptance","product_code_establishes_exact_device_identity","classification_record_establishes_marketing_authorization","classification_record_establishes_clearance_or_approval","device_class_establishes_system_conformance","classification_record_automatically_reopens_assessment"):_require(review.get(k) is False,f"{k} must remain false")
    net=p.get("network_policy") or {};_require(net.get("live_execution")=="OPT_IN_ONLY" and net.get("requires_workbench_network_gate") is True,"Network boundary changed");_require(net.get("configuration_performs_http") is False and net.get("hosted_success_claim_allowed_without_runner_steps") is False,"Execution-status boundary changed")
    return {"programme_id":p["programme_id"],"query_stream_count":len(streams),"integration_state":dep["integration_state"],"network_requests_performed":False,"exact_device_identity_claim_created":False,"authorization_claim_created":False,"canonical_mutation_performed":False}
def main()->None:print(json.dumps(validate_programme(_load(PROGRAMME_PATH),_load(UNIVERSE_REGISTRY_PATH)),indent=2,sort_keys=True))
if __name__=="__main__":main()
