"""Validate bounded openFDA UDI/GUDID discovery without network access."""
from __future__ import annotations
import json
from pathlib import Path
from typing import Any

PROGRAMME_PATH=Path("curation/openfda_udi_discovery_programme_v0.1.json")
UNIVERSE_REGISTRY_PATH=Path("curation/source_universe_registry_v0.1.json")
EXPECTED_QUERY_IDS={"DISCOVERY-OPENFDA-UDI-BCI-001","DISCOVERY-OPENFDA-UDI-DBS-NEUROSTIM-001","DISCOVERY-OPENFDA-UDI-NEUROPROSTHESIS-001","DISCOVERY-OPENFDA-UDI-VISUAL-NEUROPROSTHESIS-001","DISCOVERY-OPENFDA-UDI-NEURAL-RECORDING-001"}
REQUIRED_FIELDS={"record_identity","primary_di","primary_di_issuing_agency","record_key","record_status","public_version_number","public_version_date","public_version_status","publish_date","brand_name","company_name","version_or_model_number","catalog_number","device_description","commercial_distribution_status","commercial_distribution_end_date","identifiers","premarket_submissions","product_codes","query_memberships","normalized_record_sha256"}
REQUIRED_COVERAGE={"supplied_page_count","returned_record_count","unique_primary_di_record_count","reported_total_count","reported_total_count_state","skip_sequence_valid","skip_coverage_state","over_26000_limit","bulk_download_or_partition_required","known_controlled_duplicate_count","new_candidate_count","duplicate_representation_count","unresolved_primary_di_count","multiple_primary_di_count"}

def _load(p:Path)->Any:return json.loads(p.read_text(encoding="utf-8"))
def _require(c:bool,m:str)->None:
    if not c:raise ValueError(m)
def _universe(reg:dict[str,Any],uid:str)->dict[str,Any]:
    rows=reg.get("universes");_require(isinstance(rows,list),"Source-universe registry must contain universes");matches=[r for r in rows if r.get("universe_id")==uid];_require(len(matches)==1,f"Expected exactly one {uid} universe");return matches[0]

def validate_programme(p:dict[str,Any],reg:dict[str,Any])->dict[str,Any]:
    _require(p.get("programme_id")=="SU-REGULATION-OPENFDA-UDI-v0.1","Unexpected programme_id");_require(p.get("status")=="NONCANONICAL_PROGRAMME_CONTROL","Programme must remain noncanonical");_require(p.get("source_universe_id")=="SU-REGULATION","Programme must bind SU-REGULATION");_require(p.get("source_system")=="OPENFDA_DEVICE_UDI_GUDID","Unexpected source system");_require(_universe(reg,"SU-REGULATION").get("canonical_completeness_claim") is False,"SU-REGULATION must not claim completeness")
    provider=p.get("provider_contract") or {};_require(provider.get("provider")=="U.S. FDA openFDA Unique Device Identifier API (GUDID)","Provider changed");_require(provider.get("endpoint")=="https://api.fda.gov/device/udi.json","Endpoint changed");_require(provider.get("max_records_per_request")==1000 and provider.get("max_skip")==25000 and provider.get("max_direct_result_count")==26000,"Provider paging bounds changed");_require(provider.get("bulk_download_requires_all_files_for_complete_current_dataset") is True,"Bulk completeness boundary changed");_require(provider.get("old_records_may_change_on_provider_update") is True,"Provider update boundary changed");_require(provider.get("configuration_performs_http") is False,"Programme configuration must not perform HTTP")
    dep=p.get("workbench_dependency") or {};_require(dep.get("required_capability")=="project_openfda_udi_pages","Unexpected Workbench capability");_require(dep.get("integration_state")=="NOT_IMPLEMENTED","UDI projector must remain NOT_IMPLEMENTED until implemented")
    ident=p.get("identity_policy") or {};_require(ident.get("device_record_identity")=="PRIMARY_DI_ISSUING_AGENCY_PLUS_ID","UDI identity changed");_require(ident.get("exactly_one_primary_di_required_for_candidate") is True,"Exactly one Primary DI required");_require(ident.get("primary_di_is_gudid_record_primary_key") is True,"Primary DI primary-key boundary changed");_require(ident.get("record_key_is_provider_tracking_key_not_device_identity") is True,"record_key must remain provider tracking key");_require(ident.get("public_version_fields_track_record_updates") is True,"Public version fields must track updates");_require(ident.get("same_primary_di_changed_public_version_is_successor_observation") is True,"Version changes must be successor observations")
    for k in ("secondary_di_auto_merge","previous_di_auto_merge","direct_marking_di_auto_merge","unit_of_use_di_auto_merge","package_di_auto_merge","premarket_submission_auto_authorization_relationship","product_code_auto_system_merge","brand_name_auto_system_merge","company_name_auto_entity_merge"):_require(ident.get(k) is False,f"{k} must remain false")
    inc=p.get("inclusion_policy") or {}
    for k in ("automatic_source_admission","automatic_device_or_system_entity_creation","automatic_company_entity_creation","automatic_di_relationship_creation","automatic_premarket_authorization_relationship_creation","automatic_current_commercial_availability_claim_creation","automatic_marketing_authorization_claim_creation","automatic_effectiveness_claim_creation","automatic_system_conformance_claim_creation","automatic_assessment_mutation","automatic_reopening_decision","automatic_monitor_creation"):_require(inc.get(k) is False,f"{k} must remain false")
    _require(inc.get("human_relevance_review_required") is True,"Human review required")
    paging=p.get("paging_policy") or {};_require(paging.get("execution_mode_v0_1")=="SKIP_LIMIT_BOUNDED","Paging mode changed");_require(paging.get("page_limit")==1000 and paging.get("max_skip")==25000 and paging.get("max_direct_result_count")==26000,"Paging bounds changed");_require(paging.get("preferred_partition_field")=="public_version_date","Partition field changed");_require(paging.get("silent_truncation_allowed") is False and paging.get("partial_over_limit_candidate_emission_allowed") is False,"Silent/partial truncation prohibited");_require(paging.get("bulk_download_not_yet_authorized_by_v0_1_projector") is True,"v0.1 must not silently use bulk download")
    streams=p.get("query_streams");_require(isinstance(streams,list),"query_streams required");ids=[str(r.get("query_id") or "") for r in streams];_require(len(ids)==len(set(ids)) and set(ids)==EXPECTED_QUERY_IDS,"UDI query stream set changed")
    for r in streams:_require(r.get("cadence")=="WEEKLY" and r.get("status")=="ACTIVE",f"{r.get('query_id')}: cadence/status changed");_require(r.get("completeness_claim") is False,f"{r.get('query_id')}: cannot claim completeness");_require(isinstance(r.get("search"),str) and "device_description:" in r["search"],f"{r.get('query_id')}: device-description search required")
    proj=p.get("candidate_projection") or {};_require(set(proj.get("required_fields") or [])==REQUIRED_FIELDS,"UDI candidate field contract changed");_require(proj.get("customer_contact_fields_in_discovery_layer") is False and proj.get("labeler_duns_number_in_discovery_layer") is False and proj.get("raw_api_pages_emitted_to_s2") is False,"UDI minimization boundary changed");_require(proj.get("secondary_or_previous_di_relationships_created_in_projection") is False,"DI relationships cannot be automatic");_require(proj.get("premarket_submission_relationships_created_in_projection") is False,"Premarket relationships cannot be automatic")
    cov=p.get("coverage_contract") or {};_require(set(cov.get("required_metrics_per_leaf_query") or [])==REQUIRED_COVERAGE,"UDI coverage metrics changed");_require(cov.get("mechanical_completion_requires")=={"reported_total_count_state":"CONSISTENT","skip_sequence_valid":True,"skip_coverage_state":"MATCH","over_26000_limit":False,"bulk_download_or_partition_required":False,"unresolved_primary_di_count":0,"multiple_primary_di_count":0},"UDI mechanical completion contract changed")
    for k in ("gudid_database_completeness_claim","global_neuroai_udi_coverage_claim","query_recall_claim","gudid_presence_is_marketing_authorization_claim","commercial_distribution_status_is_independent_market_availability_proof","premarket_submission_link_is_exact_configuration_authorization_claim","primary_di_is_clinical_effectiveness_claim","primary_di_is_system_conformance_claim"):_require(cov.get(k) is False,f"{k} must remain false")
    review=p.get("human_review_contract") or {}
    for k in ("automatic_acceptance","gudid_record_is_marketing_authorization_evidence","commercial_distribution_status_is_independent_current_availability_evidence","premarket_submission_link_establishes_exact_assessed_configuration","primary_di_is_effectiveness_evidence","primary_di_is_all_configuration_conformance_evidence","udi_record_automatically_reopens_assessment"):_require(review.get(k) is False,f"{k} must remain false")
    net=p.get("network_policy") or {};_require(net.get("live_execution")=="OPT_IN_ONLY" and net.get("requires_workbench_network_gate") is True,"Network boundary changed");_require(net.get("configuration_performs_http") is False and net.get("hosted_success_claim_allowed_without_runner_steps") is False,"Execution-status boundary changed")
    return {"programme_id":p["programme_id"],"query_stream_count":len(streams),"integration_state":dep["integration_state"],"network_requests_performed":False,"marketing_authorization_claim_created":False,"current_availability_claim_created":False,"automatic_reopening":False,"canonical_mutation_performed":False}

def main()->None:print(json.dumps(validate_programme(_load(PROGRAMME_PATH),_load(UNIVERSE_REGISTRY_PATH)),indent=2,sort_keys=True))
if __name__=="__main__":main()
