"""Validate bounded openFDA PMA discovery without network access."""
from __future__ import annotations
import json
from pathlib import Path
from typing import Any
PROGRAMME_PATH=Path("curation/openfda_pma_discovery_programme_v0.1.json");UNIVERSE_REGISTRY_PATH=Path("curation/source_universe_registry_v0.1.json")
EXPECTED_QUERIES={"DISCOVERY-OPENFDA-PMA-BCI-001","DISCOVERY-OPENFDA-PMA-DBS-NEUROSTIM-001","DISCOVERY-OPENFDA-PMA-NEUROPROSTHESIS-001","DISCOVERY-OPENFDA-PMA-VISUAL-NEUROPROSTHESIS-001","DISCOVERY-OPENFDA-PMA-NEURAL-RECORDING-001"}
EXPECTED_DECISIONS={"APPR":"APPROVAL_RECORDED","WTDR":"WITHDRAWAL_RECORDED","DENY":"DENIAL_RECORDED","LE30":"THIRTY_DAY_NOTICE_ACCEPTANCE_RECORDED","APRL":"RECLASSIFICATION_AFTER_APPROVAL_RECORDED","APWD":"WITHDRAWAL_AFTER_APPROVAL_RECORDED","GT30":"NO_DECISION_WITHIN_30_DAYS_RECORDED","APCV":"CONVERSION_AFTER_APPROVAL_RECORDED"}
REQUIRED_FIELDS={"pma_number","supplement_number","record_identity","record_role","trade_name","generic_name","applicant","date_received","decision_date","decision_code","decision_semantics","product_code","supplement_type","supplement_reason","ao_statement","expedited_review_flag","query_memberships","normalized_record_sha256"}
REQUIRED_COVERAGE={"supplied_page_count","returned_record_count","unique_composite_record_count","reported_total_count","reported_total_count_state","skip_sequence_valid","skip_coverage_state","over_26000_limit","search_after_or_partition_required","out_of_scope_hde_count","out_of_scope_legacy_nda_count","known_controlled_duplicate_count","new_candidate_count","duplicate_representation_count","unresolved_pma_number_count"}
def _load(p:Path)->Any:return json.loads(p.read_text(encoding="utf-8"))
def _req(c:bool,m:str)->None:
    if not c:raise ValueError(m)
def _universe(r:dict[str,Any])->dict[str,Any]:
    rows=r.get("universes");_req(isinstance(rows,list),"registry missing universes");m=[x for x in rows if x.get("universe_id")=="SU-REGULATION"];_req(len(m)==1,"Expected one SU-REGULATION");return m[0]
def validate_programme(p:dict[str,Any],r:dict[str,Any])->dict[str,Any]:
    _req(p.get("programme_id")=="SU-REGULATION-OPENFDA-PMA-v0.1","Unexpected programme_id");_req(p.get("status")=="NONCANONICAL_PROGRAMME_CONTROL","Programme must remain noncanonical");_req(p.get("source_universe_id")=="SU-REGULATION" and p.get("source_system")=="OPENFDA_DEVICE_PMA","PMA universe/system changed");_req(_universe(r).get("canonical_completeness_claim") is False,"SU-REGULATION cannot claim completeness")
    provider=p.get("provider_contract") or {};_req(provider.get("provider")=="U.S. FDA openFDA Device PMA API" and provider.get("endpoint")=="https://api.fda.gov/device/pma.json","PMA provider changed");_req(provider.get("application_lineage_field")=="pma_number" and provider.get("supplement_record_field")=="supplement_number","PMA identity fields changed");_req(provider.get("max_records_per_request")==1000 and provider.get("max_skip")==25000 and provider.get("max_direct_result_count")==26000,"PMA paging bounds changed");_req(provider.get("configuration_performs_http") is False,"Programme cannot perform HTTP")
    dep=p.get("workbench_dependency") or {};_req(dep.get("required_capability")=="project_openfda_pma_pages","Unexpected Workbench capability");_req(dep.get("integration_state")=="NOT_IMPLEMENTED","PMA Workbench capability must remain NOT_IMPLEMENTED before implementation")
    ident=p.get("identity_policy") or {};_req(ident.get("record_identity")=="PMA_NUMBER_PLUS_SUPPLEMENT_NUMBER","PMA record identity changed");_req(ident.get("original_application_sentinel")=="ORIGINAL","Original sentinel changed");_req(ident.get("admitted_pma_prefixes")==["P","BP","D"],"PMA admitted prefixes changed");_req(ident.get("h_prefix_hde_out_of_scope_for_v0_1") is True and ident.get("n_prefix_legacy_nda_out_of_scope_for_v0_1") is True,"HDE/NDA boundaries changed")
    for k in ("same_pma_number_different_supplement_auto_merge","trade_name_auto_system_merge","applicant_auto_entity_merge","product_code_auto_system_merge","openfda_harmonized_fields_auto_identity_merge"):_req(ident.get(k) is False,f"{k} must remain false")
    decisions=p.get("decision_semantics_policy") or {};_req(decisions.get("exact_code_map")==EXPECTED_DECISIONS,"PMA decision-code map changed");_req(decisions.get("unknown_or_missing_code_state")=="UNRESOLVED_DECISION_CODE","PMA unresolved decision state changed");_req(decisions.get("approval_state_requires_exact_appr_code") is True,"Only APPR may create approval state");_req(decisions.get("supplement_approval_does_not_rewrite_original_application_record") is True,"Supplement approval cannot rewrite original");_req(decisions.get("record_presence_does_not_imply_approval") is True,"Record presence cannot imply approval")
    inc=p.get("inclusion_policy") or {}
    for k in ("automatic_source_admission","automatic_device_or_system_entity_creation","automatic_applicant_entity_creation","automatic_original_supplement_lineage_relationship_creation","automatic_current_commercial_configuration_claim_creation","automatic_global_authorization_claim_creation","automatic_system_conformance_claim_creation","automatic_assessment_mutation","automatic_reopening_decision","automatic_monitor_creation"):_req(inc.get(k) is False,f"{k} must remain false")
    paging=p.get("paging_policy") or {};_req(paging.get("execution_mode_v0_1")=="SKIP_LIMIT_BOUNDED","PMA paging mode changed");_req(paging.get("preferred_partition_field")=="decision_date","PMA partition field changed");_req(paging.get("silent_truncation_allowed") is False and paging.get("partial_over_limit_candidate_emission_allowed") is False and paging.get("search_after_not_yet_authorized_by_v0_1_projector") is True,"PMA truncation/search-after boundary changed")
    streams=p.get("query_streams");_req(isinstance(streams,list),"query_streams required");ids=[x.get("query_id") for x in streams];_req(len(ids)==len(set(ids)) and set(ids)==EXPECTED_QUERIES,"PMA query set changed")
    for x in streams:_req(x.get("cadence")=="MONTHLY" and x.get("status")=="ACTIVE" and x.get("completeness_claim") is False,f"{x.get('query_id')}: query governance changed")
    proj=p.get("candidate_projection") or {};_req(set(proj.get("required_fields") or [])==REQUIRED_FIELDS,"PMA candidate fields changed");_req(proj.get("address_or_contact_fields_in_discovery_layer") is False and proj.get("raw_api_pages_emitted_to_s2") is False,"PMA minimization changed");_req(proj.get("hde_records_emitted_as_pma_candidates") is False and proj.get("legacy_nda_records_emitted_as_pma_candidates") is False,"Out-of-scope pathway records cannot be PMA candidates");_req(proj.get("decision_semantics_derived_only_from_exact_decision_code") is True,"PMA decision semantics must derive from exact code")
    cov=p.get("coverage_contract") or {};_req(set(cov.get("required_metrics_per_leaf_query") or [])==REQUIRED_COVERAGE,"PMA coverage metrics changed");_req(cov.get("mechanical_completion_requires")=={"reported_total_count_state":"CONSISTENT","skip_sequence_valid":True,"skip_coverage_state":"MATCH","over_26000_limit":False,"search_after_or_partition_required":False},"PMA mechanical completion changed")
    for k in ("pma_database_completeness_claim","global_neuroai_pma_coverage_claim","query_recall_claim","record_presence_is_approval_claim","supplement_approval_is_original_application_approval_claim","approval_is_global_authorization_claim","approval_is_all_configuration_conformance_claim"):_req(cov.get(k) is False,f"{k} must remain false")
    review=p.get("human_review_contract") or {}
    for k in ("automatic_acceptance","record_presence_is_approval_evidence","supplement_record_automatically_changes_original_approval_scope","approval_record_is_global_authorization","approval_record_establishes_exact_current_commercial_configuration","approval_record_is_all_configuration_conformance_evidence","approval_record_automatically_reopens_assessment"):_req(review.get(k) is False,f"{k} must remain false")
    return {"programme_id":p["programme_id"],"query_stream_count":len(streams),"decision_code_count":len(EXPECTED_DECISIONS),"integration_state":dep["integration_state"],"network_requests_performed":False,"canonical_mutation_performed":False}
def main()->None:print(json.dumps(validate_programme(_load(PROGRAMME_PATH),_load(UNIVERSE_REGISTRY_PATH)),indent=2,sort_keys=True))
if __name__=="__main__":main()
