"""Validate bounded openFDA HDE discovery without network access."""
from __future__ import annotations
import json
from pathlib import Path
from typing import Any

PROGRAMME_PATH=Path("curation/openfda_hde_discovery_programme_v0.1.json")
UNIVERSE_REGISTRY_PATH=Path("curation/source_universe_registry_v0.1.json")
EXPECTED_QUERY_IDS={"DISCOVERY-OPENFDA-HDE-BCI-001","DISCOVERY-OPENFDA-HDE-DBS-NEUROSTIM-001","DISCOVERY-OPENFDA-HDE-NEUROPROSTHESIS-001","DISCOVERY-OPENFDA-HDE-VISUAL-NEUROPROSTHESIS-001","DISCOVERY-OPENFDA-HDE-NEURAL-RECORDING-001"}
EXPECTED_CODES={"APPR":"HDE_APPROVAL_RECORDED","WTDR":"WITHDRAWAL_RECORDED","DENY":"DENIAL_RECORDED","LE30":"THIRTY_DAY_NOTICE_ACCEPTANCE_RECORDED","APRL":"RECLASSIFICATION_AFTER_APPROVAL_RECORDED","APWD":"WITHDRAWAL_AFTER_APPROVAL_RECORDED","GT30":"NO_DECISION_WITHIN_30_DAYS_RECORDED","APCV":"CONVERSION_AFTER_APPROVAL_RECORDED"}
REQUIRED_FIELDS={"hde_number","supplement_number","record_identity","record_role","trade_name","generic_name","applicant","date_received","decision_date","decision_code","decision_semantics","decision_supports_hde_approval","product_code","supplement_type","supplement_reason","ao_statement","query_memberships","normalized_record_sha256"}
REQUIRED_COVERAGE={"supplied_page_count","returned_record_count","unique_composite_record_count","reported_total_count","reported_total_count_state","skip_sequence_valid","skip_coverage_state","over_26000_limit","search_after_or_partition_required","out_of_scope_non_h_prefix_count","known_controlled_duplicate_count","new_candidate_count","duplicate_representation_count","unresolved_hde_number_count"}

def _load(p:Path)->Any:return json.loads(p.read_text(encoding="utf-8"))
def _require(c:bool,m:str)->None:
    if not c:raise ValueError(m)
def _universe(reg:dict[str,Any],uid:str)->dict[str,Any]:
    rows=reg.get("universes");_require(isinstance(rows,list),"Source-universe registry must contain universes");matches=[r for r in rows if r.get("universe_id")==uid];_require(len(matches)==1,f"Expected exactly one {uid} universe");return matches[0]

def validate_programme(p:dict[str,Any],reg:dict[str,Any])->dict[str,Any]:
    _require(p.get("programme_id")=="SU-REGULATION-OPENFDA-HDE-v0.1","Unexpected programme_id");_require(p.get("status")=="NONCANONICAL_PROGRAMME_CONTROL","Programme must remain noncanonical");_require(p.get("source_universe_id")=="SU-REGULATION","Programme must bind SU-REGULATION");_require(p.get("source_system")=="OPENFDA_DEVICE_PMA_HDE_SUBSET","Unexpected source system");_require(_universe(reg,"SU-REGULATION").get("canonical_completeness_claim") is False,"SU-REGULATION must not claim completeness")
    provider=p.get("provider_contract") or {};_require(provider.get("provider")=="U.S. FDA openFDA Device PMA API — HDE subset","Provider changed");_require(provider.get("endpoint")=="https://api.fda.gov/device/pma.json","Endpoint changed");_require(provider.get("hde_record_selector")=="pma_number:H*","HDE selector changed");_require(provider.get("max_records_per_request")==1000 and provider.get("max_skip")==25000 and provider.get("max_direct_result_count")==26000,"Provider paging bounds changed");_require(provider.get("configuration_performs_http") is False,"Programme configuration must not perform HTTP")
    dep=p.get("workbench_dependency") or {};_require(dep.get("required_capability")=="project_openfda_hde_pages","Unexpected Workbench capability");_require(dep.get("integration_state")=="PENDING_S1_MERGE","Unmerged HDE projector must remain PENDING_S1_MERGE")
    identity=p.get("identity_policy") or {};_require(identity.get("record_identity")=="HDE_NUMBER_PLUS_SUPPLEMENT_NUMBER","HDE identity changed");_require(identity.get("required_hde_prefix")=="H","HDE prefix changed");_require(identity.get("non_h_prefix_records_out_of_scope") is True,"Non-H records must remain out of scope");_require(identity.get("record_content_change_is_successor_observation_not_new_record_identity") is True,"Record changes must be successor observations");
    for k in ("same_hde_number_different_supplement_auto_merge","trade_name_auto_system_merge","applicant_auto_entity_merge","product_code_auto_system_merge","openfda_harmonized_fields_auto_identity_merge"):_require(identity.get(k) is False,f"{k} must remain false")
    dec=p.get("decision_semantics_policy") or {};_require(dec.get("exact_code_map")==EXPECTED_CODES,"HDE decision map changed");_require(dec.get("hde_approval_state_requires_exact_appr_code") is True,"HDE approval must require exact APPR");_require(dec.get("record_presence_does_not_imply_hde_approval") is True,"Record presence cannot imply HDE approval");_require(dec.get("supplement_approval_does_not_rewrite_original_hde_record") is True,"Supplement approval cannot rewrite original HDE")
    auth=p.get("hde_authority_policy") or {};_require(auth.get("exact_appr_record_supports_scoped_hde_marketing_authorization") is True,"APPR scoped HDE authorization boundary changed");_require(auth.get("hde_standard_uses_probable_benefit_risk_boundary") is True,"HDE probable-benefit/risk boundary required")
    for k in ("hde_approval_does_not_establish_reasonable_assurance_of_effectiveness","hde_approval_does_not_establish_facility_irb_approval","hde_approval_does_not_establish_global_authorization","hde_approval_does_not_establish_exact_current_commercial_configuration","hde_approval_does_not_establish_all_configuration_conformance"):_require(auth.get(k) is True,f"{k} must remain true")
    inc=p.get("inclusion_policy") or {}
    for k in ("automatic_source_admission","automatic_device_or_system_entity_creation","automatic_applicant_entity_creation","automatic_original_supplement_lineage_relationship_creation","automatic_effectiveness_claim_creation","automatic_facility_irb_authorization_claim_creation","automatic_current_commercial_configuration_claim_creation","automatic_global_authorization_claim_creation","automatic_system_conformance_claim_creation","automatic_assessment_mutation","automatic_reopening_decision","automatic_monitor_creation"):_require(inc.get(k) is False,f"{k} must remain false")
    _require(inc.get("human_relevance_review_required") is True,"Human review required")
    paging=p.get("paging_policy") or {};_require(paging.get("execution_mode_v0_1")=="SKIP_LIMIT_BOUNDED","Paging mode changed");_require(paging.get("page_limit")==1000 and paging.get("max_skip")==25000 and paging.get("max_direct_result_count")==26000,"Paging bounds changed");_require(paging.get("preferred_partition_field")=="decision_date","Partition field changed");_require(paging.get("silent_truncation_allowed") is False and paging.get("partial_over_limit_candidate_emission_allowed") is False,"Silent/partial truncation prohibited");_require(paging.get("search_after_not_yet_authorized_by_v0_1_projector") is True,"v0.1 must not silently use search-after")
    streams=p.get("query_streams");_require(isinstance(streams,list),"query_streams required");ids=[str(r.get("query_id") or "") for r in streams];_require(len(ids)==len(set(ids)) and set(ids)==EXPECTED_QUERY_IDS,"HDE query stream set changed")
    for r in streams:
        qid=r["query_id"];search=r.get("search");_require(r.get("cadence")=="MONTHLY" and r.get("status")=="ACTIVE",f"{qid}: cadence/status changed");_require(r.get("completeness_claim") is False,f"{qid}: cannot claim completeness");_require(isinstance(search,str) and "+AND+pma_number:H*" in search,f"{qid}: exact HDE H-prefix filter required")
    proj=p.get("candidate_projection") or {};_require(set(proj.get("required_fields") or [])==REQUIRED_FIELDS,"HDE candidate field contract changed");_require(proj.get("address_or_contact_fields_in_discovery_layer") is False and proj.get("raw_api_pages_emitted_to_s2") is False,"HDE projection minimization changed");_require(proj.get("non_h_prefix_records_emitted_as_hde_candidates") is False,"Non-H records cannot be HDE candidates");_require(proj.get("decision_semantics_derived_only_from_exact_decision_code") is True,"Exact decision-code semantics required");_require(proj.get("effectiveness_claim_created_from_hde_approval") is False,"HDE approval cannot create effectiveness claim")
    cov=p.get("coverage_contract") or {};_require(set(cov.get("required_metrics_per_leaf_query") or [])==REQUIRED_COVERAGE,"HDE coverage metrics changed");_require(cov.get("mechanical_completion_requires")=={"reported_total_count_state":"CONSISTENT","skip_sequence_valid":True,"skip_coverage_state":"MATCH","over_26000_limit":False,"search_after_or_partition_required":False},"HDE mechanical completion contract changed")
    for k in ("hde_database_completeness_claim","global_neuroai_hde_coverage_claim","query_recall_claim","record_presence_is_hde_approval_claim","hde_approval_is_reasonable_assurance_effectiveness_claim","hde_approval_is_global_authorization_claim","hde_approval_is_all_configuration_conformance_claim"):_require(cov.get(k) is False,f"{k} must remain false")
    review=p.get("human_review_contract") or {}
    for k in ("automatic_acceptance","record_presence_is_hde_approval_evidence","hde_approval_record_is_reasonable_assurance_effectiveness_evidence","hde_approval_record_establishes_facility_irb_approval","hde_approval_record_is_global_authorization","hde_approval_record_establishes_exact_current_commercial_configuration","hde_approval_record_is_all_configuration_conformance_evidence","hde_approval_record_automatically_reopens_assessment"):_require(review.get(k) is False,f"{k} must remain false")
    net=p.get("network_policy") or {};_require(net.get("live_execution")=="OPT_IN_ONLY" and net.get("requires_workbench_network_gate") is True,"Network boundary changed");_require(net.get("configuration_performs_http") is False and net.get("hosted_success_claim_allowed_without_runner_steps") is False,"Execution-status boundary changed")
    return {"programme_id":p["programme_id"],"query_stream_count":len(streams),"integration_state":dep["integration_state"],"network_requests_performed":False,"effectiveness_claim_created":False,"facility_irb_approval_claim_created":False,"automatic_reopening":False,"canonical_mutation_performed":False}

def main()->None:print(json.dumps(validate_programme(_load(PROGRAMME_PATH),_load(UNIVERSE_REGISTRY_PATH)),indent=2,sort_keys=True))
if __name__=="__main__":main()
